### ISSUE TITLE
Users should be able to authenticate into and out of the system

### ISSUE THREAD

**Issue by zacck** [zacck/contractor#5]
### Expected Behaviour
The system has information that needs to be protected, due to this there need to be some zones so to speak that users can only access if they are authenticated and some that any user can access

### Steps to Reproduce
We need to make sure some areas of the application are only accessible to users who are signed in
areas such as 
* contract list 
* add contract page 
* edit contract page 

### Tasks
- [x] Set up communication transport for application (Graphql)
- [x] Ensure user can be created over transport 
- [x] Ensure user can login over transport 
- [ ] Ensure iser can logout over transport

**Comment by zacck** [comment]
## Notes on Setting Up Absinthe
- [ ] Set up the library and necessary artefacts (schema, types, resolvers)
- [ ] Add error handling middleware 
- [ ] Add authentication middleware
